global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
- "alert.rules"

scrape_configs:
- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'liquidsoap'
  scrape_interval: 5s
  static_configs:
  - targets:
    - liquidsoap-myradio:9001
    - liquidsoap-myradiosurround:9011
    - liquidsoap-mystreamer:9021

- job_name: 'prometheus'
  scrape_interval: 10s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node'
  scrape_interval: 5s
  static_configs:
  - targets: ['node-exporter:9100']

#- job_name: 'nodejs_app'
#  scrape_interval: 5s
#  static_configs:
#    - targets: ['host.docker.internal:3001']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'
